### ISSUE TITLE
error report_____error code -1

### ISSUE THREAD

**Issue by duperdd** [Coderx-Gamer/ui-utils#101]
When accessing any menu with this amazing modification, it seamlessly attempts to activate ui-utils, However, due to the nature of this feature, my game encountered a instability that results in a crash.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-07-12 21:43:13
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at net.minecraft.class_465.handler$zkf004$uiutils$init(class_465.java:722)
	at net.minecraft.class_465.method_25426(class_465.java:91)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:66)
	at net.minecraft.class_3929.method_17541(class_3929.java:52)
	at net.minecraft.class_634.method_17587(class_634.java:1185)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_465.handler$zkf004$uiutils$init(class_465.java:722)
	at net.minecraft.class_465.method_25426(class_465.java:91)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:66)
	at net.minecraft.class_3929.method_17541(class_3929.java:52)
	at net.minecraft.class_634.method_17587(class_634.java:1185)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 6 total; [class_746['includedDwarf96'/49527428, l='ClientLevel', x=-0.52, y=55.00, z=-89.35], class_745['§r'/9, l='ClientLevel', x=-12.59, y=54.00, z=-101.53], class_745['§r'/12, l='ClientLevel', x=11.47, y=54.00, z=-101.47], class_745['§r§r'/3, l='ClientLevel', x=-4.50, y=53.50, z=-128.50], class_745['§r§r'/6, l='ClientLevel', x=-0.50, y=53.50, z=-129.50], class_745['§r§r'/0, l='ClientLevel', x=3.50, y=53.50, z=-128.50]]
	Chunk stats: 18225, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1,55,-90), Section: (at 15,7,6 in -1,3,-6; chunk contains blocks -16,0,-96 to -1,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 948567347 game time, 741530235 day time
	Server brand: FlameCord <- RainSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 319613352 bytes (304 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2647
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37566.25
	Virtual memory used (MB): 17667.81
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 428.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.85.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.27+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.28+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.37+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+0eee1254f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.30+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.9+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.47+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.57+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.13+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.2+10ce000ff4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.4+10ce000ff4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.48+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.16+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+10ce000ff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.55+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.20+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.9+da41e1a9f4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.18+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.31+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.35+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.4+10ce000ff4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.43+10ce000ff4
			fabric-models-v0: Fabric Models (v0) 0.3.33+10ce000ff4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.4+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.44+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.1.0+d63b52eaf4
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+86d48884f4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.11+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.3+10ce000ff4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.0+c6bbc80df4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c6bbc80df4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.41+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.31+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.24+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.44+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.4+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.6+d3afe6c3f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.48+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.23+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+c956c0e6f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.2.0+10ce000ff4
		fabricloader: Fabric Loader 0.14.21
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.4
		uiutils: UI Utils 1.0.0
	Launched Version: fabric-loader-0.14.21-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 3.2.0 NVIDIA 526.47, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

**Comment by duperdd** [comment]
https://www.youtube.com/watch?v=Cc8i9yHVju0 

im also using better shulker so i cant dupe with the shulkers but it wont open and menu without crashing i have even tried isolating the mod in the mod folder i tried changing version

**Comment by duperdd** [comment]
I also used chatgpt it said The crash report suggests that an unexpected error occurred while running Minecraft. The specific error is a NoSuchMethodError, which means that the game is attempting to call a method that does not exist in the version of the game or modification you are using.
