### ISSUE TITLE
Crashes when i launch mc 1.20.1

### ISSUE THREAD

**Issue by Xerox0987** [Coderx-Gamer/ui-utils#108]
It crashes idk why i can send log here: https://paste.atlauncher.com/view/522a9fda-aedf-418b-a35d-8477f82344ba

**Comment by Xerox0987** [comment]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_5944.redirect$dem000$sodium$redirectGetUniformLocation(class_5944.java:2167)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_5944.method_34586(class_5944.java:392)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_291.method_34431(class_291.java:180)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_291.method_34427(class_291.java:123)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_286.method_43438(class_286.java:33)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_286.method_43433(class_286.java:26)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_332.method_25295(class_332.java:398)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_332.method_25297(class_332.java:378)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_332.method_25293(class_332.java:362)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_425.method_25394(class_425.java:124)
[13/08/2023 16:10:33 pm] 	at net.minecraft.class_757.method_3192(class_757.java:934)
[13/08/2023 16:10:33 pm] 	... 6 more
[13/08/2023 16:10:33 pm] [Render thread/FATAL] Reported exception thrown!
[13/08/2023 16:10:33 pm] [Render thread/INFO] [FastQuit] Exiting FastQuit.
[13/08/2023 16:10:33 pm] ---- Minecraft Crash Report ----
[13/08/2023 16:10:33 pm] // Daisy, daisy...
[13/08/2023 16:10:33 pm] 
[13/08/2023 16:10:33 pm] Time: 2023-08-13 16:10:33
[13/08/2023 16:10:33 pm] Description: Rendering overlay
[13/08/2023 16:10:33 pm] 
[13/08/2023 16:10:33 pm] java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
I think that this is the error here

**Comment by Mudxiej** [comment]
I had similar one - but it was due having outdated sodium and other rendering mods. Do you have anything else installed? Also if you are using MultiMC you can send the whole log with a button "Upload" and paste link here

**Comment by Mudxiej** [comment]
I've got the problem I guess.
I had very similar one, but there is your answer
![image](https://github.com/Coderx-Gamer/ui-utils/assets/82979937/5ef221fa-1c7d-40eb-a636-4eabd32dda86)

**Comment by Coderx-Gamer** [comment]
This seems like an issue with sodium, try running it with only ui utils and updated fabric api and let me know if it works.

**Comment by Coderx-Gamer** [comment]
First try only using ui utils and fabric api, if that doesn't work then check your ui utils version and make sure its for 1.20.1 and up to date.
