### ISSUE TITLE
Error when loading 

### ISSUE THREAD

**Issue by Dashtiss** [Coderx-Gamer/ui-utils#127]
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'UI Utils' (uiutils) 1.4.2 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
when i load in, it pops open with the error saying that, it was working before but now im just getting this error.
im running fabric 0.15.3-1.20.2

**Comment by Dashtiss** [comment]
nevermind im stupid and forgot fabric api

**Comment by MrBreakNFix** [comment]
all good!
