### ISSUE TITLE
crash on copy gui title json

### ISSUE THREAD

**Issue by shidemuri** [Coderx-Gamer/ui-utils#137]
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-06-10 18:02:29
Description: mouseClicked event handler

java.awt.HeadlessException
	at java.desktop/sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:216)
	at org.uiutils.MainClient.lambda$createWidgets$19(MainClient.java:456)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_465.method_25402(class_465.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:211)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.desktop/sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:216)
	at org.uiutils.MainClient.lambda$createWidgets$19(MainClient.java:456)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_465.method_25402(class_465.java:299)
	at net.minecraft.class_312.method_1611(class_312.java:101)
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:211)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_476
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:467)
	at net.minecraft.class_312.method_1601(class_312.java:101)
	at net.minecraft.class_312.method_22686(class_312.java:186)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:186)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:200)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:211)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1342)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 189.269s
	Wall uptime: 153.637s
	High-res time: 149.571s
	Client ticks: 2729 ticks / 136.450s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['paderoo'/6006652, l='ClientLevel', x=-1975.85, y=66.00, z=1548.70]]
	Chunk stats: 529, 392
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,100,0), Section: (at 0,4,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 413503467 game time, 269442002 day time
	Server brand: §6REDE SAINT - SEMPRE (PURGATORIO)§r (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 4

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, uiutils, wurst, server/00000000/224a2313-51c0-3bee-bc84-b1020aea9d2b
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Default font failed to load
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Default font failed to load
	at net.minecraft.class_378.method_51614(class_378.java:293)
	at net.minecraft.class_378.method_51610(class_378.java:164)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 12 more


-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 601865392 bytes (573 MiB) / 1241513984 bytes (1184 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5212
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 27077.91
	Virtual memory used (MB): 18916.77
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 899.45
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.100.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.6+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.2+bd772e83b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.2+a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.3+6e5bbc4ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+e0fdb017b0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11+a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+3cb1a7b8b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.4+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.17+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.13+8d125e3bb0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0+a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.74+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.6
		uiutils: UI Utils 1.6.0
		wurst: Wurst Client v7.42-MC1.20.6
	Launched Version: fabric-loader-0.15.11-1.20.6
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 552.12, NVIDIA Corporation
	Window size: 1920x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 8/15 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, uiutils, wurst
	Current Language: pt_br
	Locale: pt_BR
	CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
```

**Comment by MrBreakNFix** [comment]
try without wurst and lmk if that works

**Comment by oie1** [comment]
Happens to me too and I don't have wurst
[https://mclo.gs/gAo9iTB](
https://mclo.gs/gAo9iTB)

**Comment by MrBreakNFix** [comment]
Fixed in latest version 🚀
