### ISSUE TITLE
Fabricate GUI can't load on Java 17

### ISSUE THREAD

**Issue by FlorianMichael** [Coderx-Gamer/ui-utils#4]
Operating System: Windows 11
Java: 17

`java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:554)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.md778e22$lambda$init$17$0(HandledScreen.java:804)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:43)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:120)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:27)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen.java:311)
	at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.mouseClicked(AbstractInventoryScreen.java:560)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.mouseClicked(InventoryScreen.java:184)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94)
	at net.minecraft.client.Mouse.method_22686(Mouse.java:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:103)
	at net.minecraft.client.Mouse.redirect$zoa001$redirectSync(Mouse.java:1523)
	at net.minecraft.client.Mouse.method_22684(Mouse.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:123)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1205)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768)
	at net.minecraft.client.main.Main.main(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)`

**Comment by FlorianMichael** [comment]
Nevermind, another mod had headless enabled
