### ISSUE TITLE
Crash on 1.19.2 after clicking "Fabricate packets"

### ISSUE THREAD

**Issue by fabmm** [Coderx-Gamer/ui-utils#56]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2023-04-05 03:59:59
Description: mouseClicked event handler

java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at net.minecraft.class_465.mdf1793f$uiutils$lambda$init$17$0(class_465.java:9802)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_465.method_25402(class_465.java:311)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at net.minecraft.class_465.mdf1793f$uiutils$lambda$init$17$0(class_465.java:9802)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_465.method_25402(class_465.java:311)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_476
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sk1ght'/91911, l='ClientLevel', x=-2297.30, y=111.00, z=-7616.99]]
	Chunk stats: 1024, 81 F: 1898 L: 0 U: 4225
	Level dimension: minecraft:overworld
	Level spawn location: World: (646,76,251), Section: (at 6,12,11 in 40,4,15; chunk contains blocks 640,-64,240 to 655,319,255), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,-64,0 to 1023,319,511)
	Level time: 168187537 game time, 117697252 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MrBreakNFix** [comment]
r u on mac

**Comment by fabmm** [comment]
> r u on mac

Nope, windows 11

**Comment by WolfMineOfficial** [comment]
I don't understand what do you mean by "isolating the mod"??

>

**Comment by brunoman4006** [comment]
I think it refers to load just the mod

but the same thing happens on 1.19.4 1.2.2, can't verify if also happens to 1.19.3

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-07-14 14:56:43
Description: mouseClicked event handler

java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at net.minecraft.class_465.mdb66ac4$uiutils$lambda$init$19$1(class_465.java:1290)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_465.method_25402(class_465.java:293)
	at net.minecraft.class_490.method_25402(class_490.java:194)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at net.minecraft.class_465.mdb66ac4$uiutils$lambda$init$19$1(class_465.java:1290)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_465.method_25402(class_465.java:293)
	at net.minecraft.class_490.method_25402(class_490.java:194)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_490
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['brunoman4006'/1918457, l='ClientLevel', x=****, y=****, z=****]]
	Chunk stats: ***, ***
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,67,225), Section: (at 0,3,1 in -12,4,14; chunk contains blocks -192,-64,224 to -177,319,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1673780711 game time, 387469521 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:820)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 318505272 bytes (303 MiB) / 738197504 bytes (704 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 2.49
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4000
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2560.00
	Graphics card #0 deviceId: 0x0166
	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161
	Graphics card #1 name: SuperDisplay Virtual Adapter
	Graphics card #1 vendor: Software by KeloCube
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=3.47.17.59
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 16339.02
	Virtual memory used (MB): 8065.77
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 503.66
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.9.3
		clientcommands: Client Commands 2.7.13
			betterconfig: BetterConfig 1.0.7
			clientarguments: clientarguments 1.4.3
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.82.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.27+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.36+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.17+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.29+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.8+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.46+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.56+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.11+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.1+fe8721bef4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.2+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.47+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.15+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.1+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.54+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.19+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.7+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.17+1e9487d2f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.3+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.41+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.32+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.43+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.5+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.25+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.10+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.2+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.3.0+52cca24ef4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.0+52cca24ef4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.40+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.30+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.23+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.43+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.22+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.0+80d07a0af4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.1.1+b4a333d6f4
		fabric-language-kotlin: Fabric Language Kotlin 1.10.0+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.1+1.19.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 4.2.0+1.19.4
		lithium: Lithium 0.11.1
		midnightcontrols: MidnightControls 1.8.1+1.19.4
			midnightlib: MidnightLib 1.2.1
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.3
		optigui: OptiGUI 2.1.2
			optiglue: OptiGlue 2.1.2-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		starlight: Starlight 1.1.1+fabric.ae22326
		uiutils: UI Utils 1.2.2
		wurst: Wurst Client v7.35.1-MC1.19.4
	Launched Version: fabric-loader-0.14.21-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics 4000 GL version 3.2.0 - Build 10.18.10.5161, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: es_es
	CPU: 4x Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz

**Comment by Omena0** [comment]
Also crashes on 1.20.1, newest version for it.

**Comment by Coderx-Gamer** [comment]
Go to your launcher settings (or instance settings) and add "-Djava.awt.headless=false" to either the "java arguments" or "jvm arguments" text field.
