### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fortfort-rov** [Coderx-Gamer/ui-utils#92]
![image](https://github.com/Coderx-Gamer/ui-utils/assets/135806506/b79ed44c-c120-4f55-934f-aafbe104fe22)
I have fabric properly installed, but it shows this when I boot up fabric with ui-utils.
=-Error info-=
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'UI Utils' (uiutils) 1.3.1 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MrBreakNFix** [comment]
You also need fabric API

**Comment by Coderx-Gamer** [comment]
Make sure FabricMC and Fabric API are up to date.
